### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by muzena** [Colossal1/plugin.video.bennu#3]
@Kr1ss-XD
Can you look this.
On first start it works all.
After that there is missing all thumbnail (movie, TV show...)
And i think on first run there was in Cerus > TV SHOWS
1970'S category, now is missing

**Comment by Colossal1** [comment]
Muzena are you on keybase chat?

**Comment by Kr1ss-XD** [comment]
I'm not actually working on Bennu @muzena 
Just helping out with Covenant as much as I can

**Comment by muzena** [comment]
@Colossal1 
> Muzena are you on keybase chat?
Why do you ask?
